format = """
[╭  ](fg:green)\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$kubernetes \
$time \
$battery \
\n$character"""

[character]
format = """
[╰─$symbol](fg:green) """
success_symbol = '[](fg:bold green)'
error_symbol = '[](fg:bold red)'

[directory]
format = '[$path](fg:green)'
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
disabled = false
symbol = ""
format = '( | [$symbol](fg:green) $branch)'
[git_commit]
disabled = false
format = '( | [\($hash$tag\)](fg:white))'
[git_state]
disabled = false
format = '( | [\($state( $progress_current/$progress_total)\)](fg:white))'
[git_status]
disabled = false
format = '([ ](fg:white)$conflicted$staged$modified$renamed$deleted$untracked$stashed$ahead_behind)'
conflicted = "[ ](bold fg:red)[  ${count} ](fg:white)"
staged = "[ $count ](fg:magenta)"
modified = "[ ${count} ](fg:magenta)"
renamed = "[ ${count} ](fg:white)"
deleted = "[ ${count} ](fg:red)"
untracked = "[?${count} ](fg:white)"
stashed = "[ ${count} ](fg:white)"
ahead = "[ ${count} ](fg:red)"
behind = "[ ${count} ](fg:cyan)"
diverged = "[ ](bold fg:red)[ נּ ](fg:cyan)[ ${ahead_count} ](fg:red)[ ${behind_count} ](fg:cyan)"

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
format = '| $time'

[battery]
format = "[$symbol$percentage ]($style)"
[[battery.display]]
threshold = 20
style = "bold red"
