# General parameters
[config]
reload_apps = true
run_after = [["touch", "~/.config/alacritty/alacritty.toml"],]

[config.reload_apps_list]
gtk_theme = true

# i3
[templates.i3]
input_path = '~/afs/.confs/config/matugen/templates/i3.conf'
output_path = '~/afs/.confs/config/i3/colors.conf'
post_hook = 'i3 reload > /dev/null'

# Polybar
[templates.polybar]
input_path = '~/afs/.confs/config/matugen/templates/polybar.ini'
output_path = '~/afs/.confs/config/polybar/colors.ini'
post_hook = 'polybar-msg cmd restart > /dev/null'

# Rofi
[templates.rofi]
input_path = '~/afs/.confs/config/matugen/templates/rofi.rasi'
output_path = '~/afs/.confs/config/rofi/colors.rasi'

# Alacritty
[templates.alacritty]
input_path = '~/afs/.confs/config/matugen/templates/alacritty.toml'
output_path = '~/afs/.confs/config/alacritty/colors.toml'

# Pywalfox
[templates.pywalfox]
input_path = '~/afs/.confs/config/matugen/templates/pywalfox.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

# Gtk 3
[templates.gtk3]
input_path = '~/afs/.confs/config/matugen/templates/gtk.css'
output_path = '~/afs/.confs/config/gtk-3.0/colors.css'

# Gtk4
[templates.gtk4]
input_path = '~/afs/.confs/config/matugen/templates/gtk.css'
output_path = '~/afs/.confs/config/gtk-4.0/colors.css'

# Qt 5
[templates.qt5ct]
input_path = "~/afs/.confs/config/matugen/templates/qtct.conf"
output_path = "~/afs/.confs/config/qt5ct/colors/matugen.conf"

# Qt 6
[templates.qt6ct]
input_path = "~/afs/.confs/config/matugen/templates/qtct.conf"
output_path = "~/afs/.confs/config/qt6ct/colors/matugen.conf"

